### ISSUE TITLE
Strict requirement on PHP >= 5.6

### ISSUE THREAD

**Issue by sgehrig** [graphaware/neo4j-bolt-php#10]
Why is there a strict requirement on PHP >= 5.6? I quickly scanned the code and could not find any trace of any of the PHP 5.6-only features being used,

I know that PHP 5.5 is going to reach end of life shortly, but unfortunately it's still a given fact we have to deal with as our code is still being run on Ubuntu 14.04 for example. 

If there isn't a strict dependency on PHP >= 5.6 could this be changed to PHP >= 5.5?

**Comment by ikwattro** [comment]
Refer to https://github.com/graphaware/neo4j-php-client#47 for the answer, closing this.
