### ISSUE TITLE
Infinite loop on session

### ISSUE THREAD

**Issue by bitgandtter** [graphaware/neo4j-bolt-php#15]
Im having an infinite loop on session **recv** function that i track to lines [`170 and 171 of Session.php file`](https://github.com/graphaware/neo4j-bolt-php/blob/1470f24967a399466edfea49e340df3950bd1c04/src/Protocol/V1/Session.php#L170)

the queries im running are:

```
$stack = $this->neo4jClient->stack();
$stack->push("CREATE CONSTRAINT ON (person:Person) ASSERT person.mongoID IS UNIQUE");
$stack->push(
                "CREATE (person:Person) SET person += {info}",
                array('info' => array('mongoID' => (string)$person->getId()))
);
$this->neo4jClient->runStack($stack);
```

Where the person already exist on database

**Comment by ikwattro** [comment]
can you specify the neo4j version you are using ?

**Comment by bitgandtter** [comment]
version 3.1, i dont think related but im using it with the official docker image

**Comment by ikwattro** [comment]
@bitgandtter can you try with last release 1.8.1 ? Thanks

**Comment by bitgandtter** [comment]
@ikwattro now it throws this exception when trying to collect statistics

`Argument 1 passed to GraphAware\Common\Result\CombinedStatistics::mergeStats() must implement interface GraphAware\Common\Result\StatementStatisticsInterface, null given`

**Comment by bitgandtter** [comment]
I track the issue to the point that because the stack is running a query that does not provide **updateStatistics** it breaks. 

`$stack->push("CREATE CONSTRAINT ON (person:Person) ASSERT person.mongoID IS UNIQUE");`

We have two options here, or update the **updateStatistics** function of the ResultCollection to handle this or to not include on the collection results that does not has **updateStatistics** on the **run** function of **Pipeline** class

**Comment by ikwattro** [comment]
yeah, fixed in common 

```
composer update graphaware/neo4j-common
```

thx

**Comment by bitgandtter** [comment]
Great it works now, thanks
