### ISSUE TITLE
Accidental var_dump()?

### ISSUE THREAD

**Issue by sgehrig** [graphaware/neo4j-bolt-php#16]
I don't think that this has been done deliberately in `src/Protocol/V1/Session.php` lines 181 - 184:

```php
if ($shouldThrow !== false) {
    var_dump("cooollll");
    throw $shouldThrow;
}
```

**Comment by ikwattro** [comment]
haha good point :) var_dump driven dev. Thnaks

**Comment by ikwattro** [comment]
removed in 1.8.2
