### ISSUE TITLE
Timeout when submitting a null query

### ISSUE THREAD

**Issue by saburo70** [graphaware/neo4j-bolt-php#7]
Debian 8, php5-fpm, neo3.0.1

Normally a query text should not be null, but I think it would be better to return a null or something from Session->run($query)  if $query==null.

Currently the driver hangs on for long time, generating quite some load on php5-fpm processes

**Comment by ikwattro** [comment]
Thanks, this is interesting. Normally php should throw an exception due to a missing argument. I'll investigate that.

**Comment by ikwattro** [comment]
@saburo70 Can you paste the snippet of code you are using, actually for me it throws an exception immediately : 

```
ikwattro@graphaware ~/d/g/p/neo4j-bolt-php> php test.php
PHP Fatal error:  Uncaught exception 'GraphAware\Bolt\Exception\MessageFailureException' with message 'Unable to read MSG_RUN message. Error was: Wrong type received. Expected STRING, received: NULL (0xff).' in /Users/ikwattro/dev/graphaware/php/neo4j-bolt-php/src/Protocol/V1/Response.php:66
Stack trace:
#0 /Users/ikwattro/dev/graphaware/php/neo4j-bolt-php/src/Protocol/V1/Session.php(87): GraphAware\Bolt\Protocol\V1\Response->onFailure(Object(GraphAware\Bolt\PackStream\Structure\Structure))
#1 /Users/ikwattro/dev/graphaware/php/neo4j-bolt-php/test.php(8): GraphAware\Bolt\Protocol\V1\Session->run(NULL)
#2 {main}
  thrown in /Users/ikwattro/dev/graphaware/php/neo4j-bolt-php/src/Protocol/V1/Response.php on line 66

Fatal error: Uncaught exception 'GraphAware\Bolt\Exception\MessageFailureException' with message 'Unable to read MSG_RUN message. Error was: Wrong type received. Expected STRING, received: NULL (0xff).' in /Users/ikwattro/dev/graphaware/php/neo4j-bolt-php/src/Protocol/V1/Response.php on line 66

GraphAware\Bolt\Exception\MessageFailureException: Unable to read MSG_RUN message. Error was: Wrong type received. Expected STRING, received: NULL (0xff). in /Users/ikwattro/dev/graphaware/php/neo4j-bolt-php/src/Protocol/V1/Response.php on line 66
```

Code I'm using : 

``` php
<?php

require_once __DIR__.'/vendor/autoload.php';

$driver = \GraphAware\Bolt\GraphDatabase::driver("bolt://localhost");
$session = $driver->session();

$session->run(null);
```

**Comment by saburo70** [comment]
I get 

 0.2381ms

## Connected

Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/pack/vendor/graphaware/neo4j-bolt/src/PackStream/StreamChannel.php on line 71
`<?
  ini_set('display_errors', TRUE);
  ini_set('display_startup_errors', TRUE);
  require_once  "/var/www/pack/vendor/autoload.php";
  $t1 = microtime();
  try
   {
    $basic_auth = GraphAware\Bolt\Configuration::withCredentials("neo4j","mypass");
    $uri = "bolt://192.168.1.115:7687";
    $conn = GraphAware\Bolt\GraphDatabase::driver($uri,$basic_auth) 
            ->session(); 
    if (!$conn) $conn=false;
   } catch (Exception $e) { 
    $conn = false;
    var_dump($e);
   }
   echo ((microtime()-$t1)*100)."ms<br>";
   $t1 = microtime();

   echo "Connected<hr>";
   $q = null;  
   try { $ret = $conn->run($q); } 
   catch (Exception $e) {
       echo "Exception : ".((microtime()-$t1)_100)."ms<br>";
       $ret = null; 
       var_dump($e);
      }
   echo "<br>";
   echo ((microtime()-$t1)_100)."ms<br>";
   $t1 = microtime();
   echo "<br>Done.";
?>`

**Comment by saburo70** [comment]
Sorry, formatting issues
`
<?
  ini_set('display_errors', TRUE);
  ini_set('display_startup_errors', TRUE);
  require_once  "/var/www/pack/vendor/autoload.php";
  $t1 = microtime();
  try
   {
    $basic_auth = GraphAware\Bolt\Configuration::withCredentials("neo4j","mypassword");
    $uri = "bolt://192.168.1.115:7687";
    $conn = GraphAware\Bolt\GraphDatabase::driver($uri,$basic_auth) 
            ->session(); 
    if (!$conn) $conn=false;
   } catch (Exception $e) { 
    $conn = false;
    var_dump($e);<br>
   }
   echo ((microtime()-$t1)*100)."msms&lt:br&gt;";
   $t1 = microtime();

   echo "Connectedms&lt:br&gt;";
   $q = null;  
   try { $ret = $conn->run($q); } 
   catch (Exception $e) {
       echo "Exception : ".((microtime()-$t1)_100)."ms&lt:br&gt;";
       $ret = null; 
       var_dump($e);
      }
   echo "&lt:br&gt;";
   echo ((microtime()-$t1)_100)."ms&lt:br&gt;";
   $t1 = microtime();
   echo "ms&lt:br&gt;Done.";
?>
`

**Comment by ikwattro** [comment]
Thanks, I could reproduce it but intermittently, I'll have to investigate if it is at the client side of the binary channel or at the neo4j server side that it hands.

As a more secure fix, I will check for null and throw an exception so null cannot be sent over the wire as query.

Thanks again for the report

**Comment by saburo70** [comment]
Thank you, on my side I use a wrapper function to run a query, so I trap null queries upfront.
As a general idea maybe in the 
``
      while ($remaining > 0) {
            //$this->io->wait();
            $new = $this->io->readChunk();
            $this->bytes .= $new;
            $remaining -= strlen($new);
        }

```
it might be safer to add a sort of watchdog that bails out from the loop after n iterations
```

**Comment by ikwattro** [comment]
Yeah, the problem is `ticking()` can be 1000s in a microsecond, it's hard to tell after how many times it should stop the iteration. But the idea can be ported to a time based timeout and throw an exception.
